const config = require('config')
const paymentConfig = config.get("payment")

module.exports = {
    BUY_WITH_CREDIT_CARD_BUTTON: paymentConfig.BUY_WITH_CREDIT_CARD_BUTTON,
    BUY_WITH_CREDIT_CARD_LABEL: paymentConfig.BUY_WITH_CREDIT_CARD_LABEL,
    CREDIT_CARD_NUMBER_INPUT: paymentConfig.CREDIT_CARD_NUMBER_INPUT,
    CREDIT_CARD_EXPIRATION_DATE_INPUT: paymentConfig.CREDIT_CARD_EXPIRATION_DATE_INPUT,
    CREDIT_CARD_CVC_INPUT: paymentConfig.CREDIT_CARD_CVC_INPUT,
    PAY_BUTTON: paymentConfig.PAY_BUTTON,
    PAYMENT_SUCESSFUL_LABEL: paymentConfig.PAYMENT_SUCESSFUL_LABEL,
    DONE_BUTTON: paymentConfig.DONE_BUTTON,
    USE_DIFFERENT_CARD_BUTTON: paymentConfig.USE_DIFFERENT_CARD_BUTTON,
    BUY_WITH_ETH_BUTTON: paymentConfig.BUY_WITH_ETH_BUTTON,
    CONFIRM_BUTTON: paymentConfig.CONFIRM_BUTTON,
};    