const config = require('config')
const racingConfig = config.get("racing")

module.exports = {
    RACING_EVENT_LIST: racingConfig.RACING_EVENT_LIST,
    SELECTED_RACING_EVENT : racingConfig.SELECTED_RACING_EVENT,
    SELECTED_GATE_REGISTERED_INFO: racingConfig.SELECTED_GATE_REGISTERED_INFO,
    SELECTED_RACING_EVENT_GATE_HEADER : racingConfig.SELECTED_RACING_EVENT_GATE_HEADER,
    SELECTED_RACING_EVENT_OPEN_GATES_LIST: racingConfig.SELECTED_RACING_EVENT_OPEN_GATES_LIST,
    SELECTED_RACING_EVENT_NAME : racingConfig.SELECTED_RACING_EVENT_NAME,

};    