const config = require('config')
const studServiceConfig = config.get("studService")

module.exports = {
    MALE_HORSE_LIST: studServiceConfig.MALE_HORSE_LIST,
    SELECTED_MALE_HORSE: studServiceConfig.SELECTED_MALE_HORSE,
    SELECTED_SELECT_MATE_BUTTON: studServiceConfig.SELECTED_SELECT_MATE_BUTTON,
    SELECTED_HORSE_NAME : studServiceConfig.SELECTED_HORSE_NAME,
    STUD_MALE_HORSE_NAME: studServiceConfig.STUD_MALE_HORSE_NAME,
    SELECT_FEMALE_BUTTON: studServiceConfig.SELECT_FEMALE_BUTTON,
    SELECT_FEMALE_POPUP_HEADER: studServiceConfig.SELECT_FEMALE_POPUP_HEADER,
    FEMALE_HORSE_LIST : studServiceConfig.FEMALE_HORSE_LIST,
    SELECTED_FEMALE_HORSE : studServiceConfig.SELECTED_FEMALE_HORSE,
    SELECTED_FEMALE_NAME : studServiceConfig.SELECTED_FEMALE_NAME,
    SELECTED_FEMALE_SELECT_BUTTON : studServiceConfig.SELECTED_FEMALE_SELECT_BUTTON,
    SELECT_FEMALE_HORSE_NAME : studServiceConfig.SELECT_FEMALE_HORSE_NAME,
    BUY_COVER_BUTTON: studServiceConfig.BUY_COVER_BUTTON,
    CONFIRM_BUTTON: studServiceConfig.CONFIRM_BUTTON,
    CHECK_ACTIVITY_BUTTON: studServiceConfig.CHECK_ACTIVITY_BUTTON,
};    