module.exports = {
    LOGIN_START_BUTTON: "div.start-part",
    EMAIL_INPUT: "div.m-input-content > input[placeholder='Email']",
    CONTINUE_BUTTON: "button[type='Submit']",
    AUTHENTICATE_BUTTON: "//button[text()='authenticate']",
    WELCOME_LABEL: "//h1[text()='Welcome To Zed!']",
    TRUST_ME_BUTTON: "//div[contains(@class,'auth-anomaly-detected__actionRack')]/span[@role='button' and descendant::text()='Yes, this is me']",
    LOGIN_SUCESSFUL_MESSAGE: "//h1/p[contains(text(),'logged into ZED Run!')]",
    CONNECT_METAMASK: "//div[text()='Connect Metamask']",
    ACCEPT_BUTTON: "text='Accept'",
    MARKETPLACE_LINK: "//div[@class='header-desktop']//div[@class='header-content']//div[text()='Marketplace']",
    LOGIN_POPUP: "#login-modal #login-steps .start-modal-content",
    USER_AVATAR: ".header-desktop .header-content div.right-part  div.user-part > div.icon-part img",
    ARROW_ICON: ".icon-arrow",
    BREEDING_LINK: "//div[@class='header-desktop']//div[@class='left-part']//a[descendant::text()='BREEDING']",
    STUD_SERVICE_LINK: "text='Stud Service'",
    RACING_LINK: "//div[@class='header-desktop']//div[@class='left-part']/div[@data-tour='header-racing']//a[descendant::text()='racing']",
    BALANCE_LOADER_ICON: ".header-desktop .header .header-content .right-part .balance-part div.loader-container.stud-loader",
    ETH_BALANCE: ".header-desktop .header .header-content .right-part .balance-part .right b:nth-child(1)",
    ZED_BALANCE: ".header-desktop .header .header-content .right-part .balance-part .right b:nth-child(2)",
    MY_STABLE_LINK: "//div[contains(@class,'user-menu')]/div[@role='menu']/div[@role='menuitem' and descendant::text()='My Stable']/a",
    BALANCE_INFO: ".header-desktop .header .header-content .right-part .balance-part .right b",
    PROFILE_ICON: ".right-part .menu-button .icon-arrow img",
    MY_STABLE: "//div[contains(@class, 'menu-content')]//span[contains(text(), 'My Stable')]"
};