name: ZED Test Automation (Auto Assign)
on:
  pull_request:
    types: [ opened, reopened, ready_for_review ]

env:
  FORCE_COLOR: 1
  GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}

jobs:
  auto-assignation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: kentaro-m/auto-assign-action@v1.2.1
        if: ${{ always()}}
        with:
          configuration-path: .github/auto_assign.yml
      - uses: madrapps/add-reviewers@v1
        if: ${{ always()}}
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          reviewers: jbricenoz
          re-request-when-approved: true
          re-request-when-changes-requested: true
      - uses: actions-ecosystem/action-add-labels@v1
        if: ${{ always()}}
        with:
          labels: UI_TEST
#      - uses: srggrs/assign-one-project-github-action@1.2.1
#        if: ${{ always()}}
#        with:
#          project: 'https://github.com/orgs/vhslab/projects/3'
