name: automation test CI

on:
  repository_dispatch:
  push:
  schedule:
    - cron: '0 0 * * *'  # every day at midnight

  #repository_dispatch:
  #push:

jobs:
  run-test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: microsoft/playwright-github-action@v1
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: Run test when have event ping
      if: ${{ always()}}
      # if: github.event.action == 'ping'
      run: |
        echo "action '${{ github.event.action }}' "
        echo "repository '${{ github.event.client_payload.repository }}' "
        npm ci
        npm install
        xvfb-run --auto-servernum -- npm run test
      env:
        CI: true
    - name: Get Allure history
      uses: actions/checkout@v2
      if: always()
      continue-on-error: true
      with:
        ref: gh-pages
        path: gh-pages

    - name: Allure Report action from marketplace
      uses: simple-elf/allure-report-action@master
      if: always()
  #id: allure-report
      with:
        allure_results: allure-results
        #gh_pages: gh-pages
        #allure_report: allure-report
        allure_history: allure-history
    - name: Deploy report to Github Pages
      if: always()
      uses: peaceiris/actions-gh-pages@v2
      env:
        PERSONAL_TOKEN: 07a56d6a3c3b39cc83c0375fedf5070e4b60a4cf
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: allure-history

    - name: Screenshot Test Report
      uses: swinton/screenshot-website@v1.x
      with:
        source: https://vhslab.github.io/qa-automationtest/
        destination: screenshot.png
        full-page: true
        
    # - name: Send url test report to Slack
    #   if: always()
    #   uses: archive/github-actions-slack@v1.0.3
    #   id: notify
    #   with:
    #     slack-bot-user-oauth-access-token: ${{ secrets.SLACK_BOT_USER_OAUTH_ACCESS_TOKEN }}
    #     slack-channel: "automation-test-report"
    #     slack-text: check your report detail here https://vhslab.github.io/qa-automationtest/
    - name: create file  
      run: |
        echo "Test file " > test.txt
    - name: Slack File Upload
      uses: adrey/slack-file-upload-action@1.0.5
      with:
        token: ${{ secrets.SLACK_BOT_USER_OAUTH_ACCESS_TOKEN }}
        path: text.txt
        channel: automation-test-report