name: ZED Test Automation (Develop)
on:
  push:
    branches:
      - develop

env:
  # Force terminal colors. @see https://www.npmjs.com/package/colors
  FORCE_COLOR: 1

jobs:
  e2e-tests:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: microsoft/playwright-github-action@v1
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '14.x'
    - name: Run test when have event ping
      if: ${{ always()}}
      # if: github.event.action == 'ping'
      run: |
        npm ci
        npm install
        variable=$(git rev-parse --short HEAD)
        echo "Last commit registred:" $variable
        xvfb-run --auto-servernum -- npm run test
      env:
        CI: true
    - name: Get Allure history
      uses: actions/checkout@v2
      if: always()
      continue-on-error: true
      with:
        ref: gh-pages
        path: gh-pages
    - name: Allure Report action from marketplace
      uses: simple-elf/allure-report-action@master
      if: always()
      #id: allure-report
      with:
        allure_results: allure-results
        gh_pages: gh-pages
        allure_report: allure-report
        allure_history: allure-history
    - name: Deploying Allure Report to Github Pages
      if: always()
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.ACCESS_TOKEN }}
        publish_branch: gh-pages
        allow_empty_commit: true
        publish_dir: allure-history
        user_name: 'github-actions[bot]'
        user_email: 'github-actions[bot]@users.noreply.github.com'
        commit_message: ${{ github.event.head_commit.message }}
    - name: Record Video On Failure
      uses: actions/upload-artifact@v2
      if: ${{ failure() }}
      with:
        name: Recordings
        path: videos/
        retention-days: 3
    - name: See
      if: ${{ always()}}
      # if: github.event.action == 'ping'
      run: |
        pwd
        ls
        cd videos/
        ls
    - name: Upload artifact to Slack Channel
      if: always()
      uses: adrey/slack-file-upload-action@1.0.5
      with:
        token: ${{ secrets.SLACK_BOT_USER_OAUTH_ACCESS_TOKEN }}
        path: /home/runner/work/qa-automationtest/qa-automationtest/videos/Recordings.zip
        channel: automation-test-report
    - name: Upload message with Allure Report URL to Slack Channel
      if: always()
      uses: archive/github-actions-slack@v1.0.3
      id: notify
      with:
        slack-bot-user-oauth-access-token: ${{ secrets.SLACK_BOT_USER_OAUTH_ACCESS_TOKEN }}
        slack-channel: "automation-test-report"
        slack-text: Development Report https://vhslab.github.io/qa-automationtest/
