name: ZED Test Automation (Develop Auto Assign)
on:
  pull_request:
    types: [ opened, ready_for_review ]

env:
  # Force terminal colors. @see https://www.npmjs.com/package/colors
  FORCE_COLOR: 1

jobs:
  e2e-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: kentaro-m/auto-assign-action@v1.2.1
        with:
          addReviewers: jbricenoz
          addAssignees: author
          numberOfReviewers: 1

