name: ZED Test Automation (Develop Auto Assign)
on:
  pull_request:
    types:
      - opened
      - ready_for_review
    branches:
      - 'feature/**'

env:
  # Force terminal colors. @see https://www.npmjs.com/package/colors
  FORCE_COLOR: 1

jobs:
  e2e-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: kentaro-m/auto-assign-action@v1.2.1
        with:
          addReviewers: true
          addAssignees: author
          reviewers: jbricenoz
          numberOfReviewers: 1

