name: Node.js CI

on: [
  repository_dispatch,
  push 
] 
  
jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: microsoft/playwright-github-action@v1
    
#     - name: Set up JDK
#       uses: actions/setup-java@v1
#       with:
#         java-version: 1.8 

    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'

#     - name: Get Allure history
#       uses: actions/checkout@v2
#       if: always()
#       continue-on-error: true
#       with:
#         ref: gh-pages
#         path: gh-pages 
    

    - name: Run test when have event ping
      run: |
        npm ci
        npm test
        allure generate
        npm install
        npm run test 

      env:
        CI: true