# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# jobs:
#   build:
 
#     runs-on: ubuntu-latest
  
#     steps:
#     - uses: actions/checkout@v2
#     - uses: microsoft/playwright-github-action@v1
    
#     - name: Use Node.js
#       uses: actions/setup-node@v1
#       with:
#         node-version: '12.x'
        
#     - name: Run test when have event ping
#       run: 
#         npm install
#         npm run test tests/magicLink.test.js
#       env:
#         CI: true
jobs:
  e2e-tests:
    runs-on: ubuntu-latest # or macos-latest, windows-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1

      - uses: microsoft/playwright-github-action@v1

      - name: Install dependencies and run tests
        run: npm install && npm test